export const RESET_STATE = 'ECOMMERCE_RESET_STATE';
export const CURRENT_ITEM = 'ECOMMERCE_CURRENT_ITEM';

export const REQUEST_LOADING = 'ECOMMERCE_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'ECCOMMERCE_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'ECOMMERCE_REQUEST_FAILED';

export const CURRENT_ACTION = 'ECOMMERCE_CURRENT_ACTION';
export const RESET_ACTION = 'ECOMMERCE_RESET_ACTION';

export const ADD_TO_CART = 'ECOMMERCE_ADD_TO_CART';
export const REMOVE_FROM_CART = 'ECOMMERCE_REMOVE_FROM_CART';
export const OPEN_CART = 'ECOMMERCE_OPEN_CART';
