export const RESET_STATE = 'STOCK_RESET_STATE';
export const CURRENT_ITEM = 'STOCK_CURRENT_ITEM';

export const REQUEST_LOADING = 'STOCK_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'STOCK_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'STOCK_REQUEST_FAILED';

export const CURRENT_ACTION = 'STOCK_CURRENT_ACTION';
export const RESET_ACTION = 'STOCK_RESET_ACTION';
export const SET_PRODUCT_IMAGE_MAP = 'SET_PRODUCT_IMAGE_MAP';
