export const RESET_STATE = 'TRAVELS/RESET_STATE';
export const REQUEST_LOADING = 'TRAVELS/REQUEST_LOADING';
export const REQUEST_SUCCESS = 'TRAVELS/REQUEST_SUCCESS';
export const REQUEST_FAILED = 'TRAVELS/REQUEST_FAILED';
export const CURRENT_ITEM = 'TRAVELS/CURRENT_ITEM';
export const RESET_ACTION = 'TRAVELS/RESET_ACTION';
export const CURRENT_ACTION = 'TRAVELS/CURRENT_ACTION';


