export const RESET_STATE = 'SALES_RESET_STATE';
export const CURRENT_ITEM = 'SALES_CURRENT_ITEM';

export const REQUEST_LOADING = 'SALES_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'SALES_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'SALES_REQUEST_FAILED';

export const CURRENT_ACTION = 'SALES_CURRENT_ACTION';
export const RESET_ACTION = 'SALES_RESET_ACTION';

export const UPDATE_ORDER_OPTIONS = 'UPDATE_ORDER_OPTIONS';
export const UPDATE_PAYMENT_OPTIONS = 'UPDATE_PAYMENT_OPTIONS';
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
