export const RESET_STATE = 'VEHICLES/RESET_STATE';
export const REQUEST_LOADING = 'VEHICLES/REQUEST_LOADING';
export const REQUEST_SUCCESS = 'VEHICLES/REQUEST_SUCCESS';
export const REQUEST_FAILED = 'VEHICLES/REQUEST_FAILED';
export const CURRENT_ITEM = 'VEHICLES/CURRENT_ITEM';
export const RESET_ACTION = 'VEHICLES/RESET_ACTION';
export const CURRENT_ACTION = 'VEHICLES/CURRENT_ACTION';
