const tags = {
  TIPO: [
    'Zapatos',
    'Botas',
    'Zapatillas',
    'Sandalias',
    'Mocasines',
    'Tacones',
    'Alpargatas',
  ],
  MATERIAL: ['Cuero', 'Gamuza', 'Sintético', 'Lona', 'Tela', 'Malla', 'Plástico', 'Caucho'],
  ESTILO: [
    'Casual',
    'Deportivo',
    'Formal',
    'Elegante',
    'Urbano',
    'Bohemio',
    'Retro',
    'Clásico',
    'Moderno',
  ],
  TEMPORADA: ['Verano', 'Invierno', 'Primavera', 'Otoño'],
  COLOR: [
    'Negro',
    'Blanco',
    'Marrón',
    'Azul',
    'Plata',
    'Rojo',
    'Verde',
    'Gris',
    'Beige',
    'Camel',
    'Ceniza',
  ],
  CARACTERISTICAS: [
    'Impermeable',
    'Transpirable',
    'Antideslizante',
    'Con plataforma',
    'Sin cordones',
    'Con hebilla',
    'Con cierre',
    'Puntera reforzada',
  ],
  USO: ['Diario', 'Deporte', 'Oficina', 'Fiesta', 'Al aire libre', 'Viaje', 'Trabajo'],
  GENERO: ['Hombre', 'Mujer', 'Unisex', 'Niños', 'Niñas'],
  LINEA: ['Sportech', 'Lady', 'Casual', 'Económica'],
};

export default tags;
