const tagsArray = [
  { id: 1, name: 'Zapatos', category: 'TIPO' },
  { id: 2, name: 'Botas', category: 'TIPO' },
  { id: 3, name: 'Zapatillas', category: 'TIPO' },
  { id: 4, name: 'Sandalias', category: 'TIPO' },
  { id: 5, name: 'Mocasines', category: 'TIPO' },
  { id: 7, name: 'Cuero', category: 'MATERIAL' },
  { id: 8, name: 'Gamuza', category: 'MATERIAL' },
  { id: 9, name: 'Sintético', category: 'MATERIAL' },
  { id: 10, name: 'Lona', category: 'MATERIAL' },
  { id: 11, name: 'Tela', category: 'MATERIAL' },
  { id: 12, name: 'Malla', category: 'MATERIAL' },
  { id: 13, name: 'Plástico', category: 'MATERIAL' },
  { id: 14, name: 'Caucho', category: 'MATERIAL' },
  { id: 15, name: 'Casual', category: 'ESTILO' },
  { id: 16, name: 'Deportivo', category: 'ESTILO' },
  { id: 17, name: 'Elegante', category: 'ESTILO' },
  { id: 18, name: 'Urbano', category: 'ESTILO' },
  { id: 19, name: 'Clásico', category: 'ESTILO' },
  { id: 20, name: 'Moderno', category: 'ESTILO' },
  { id: 25, name: 'Negro', category: 'COLOR' },
  { id: 26, name: 'Blanco', category: 'COLOR' },
  { id: 27, name: 'Marrón', category: 'COLOR' },
  { id: 28, name: 'Azul', category: 'COLOR' },
  { id: 29, name: 'Plata', category: 'COLOR' },
  { id: 30, name: 'Rojo', category: 'COLOR' },
  { id: 31, name: 'Verde', category: 'COLOR' },
  { id: 32, name: 'Gris', category: 'COLOR' },
  { id: 33, name: 'Beige', category: 'COLOR' },
  { id: 34, name: 'Camel', category: 'COLOR' },
  { id: 35, name: 'Ceniza', category: 'COLOR' },
  { id: 36, name: 'Impermeable', category: 'CARACTERISTICAS' },
  { id: 37, name: 'Transpirable', category: 'CARACTERISTICAS' },
  { id: 38, name: 'Antideslizante', category: 'CARACTERISTICAS' },
  { id: 50, name: 'Hombre', category: 'GENERO' },
  { id: 51, name: 'Mujer', category: 'GENERO' },
  { id: 52, name: 'Unisex', category: 'GENERO' },
  { id: 53, name: 'Niños', category: 'GENERO' },
  { id: 55, name: 'Sportech', category: 'LINEA' },
  { id: 56, name: 'Lady', category: 'LINEA' },
  { id: 57, name: 'Casual', category: 'LINEA' },
  { id: 59, name: 'Urban', category: 'LINEA' },
  { id: 60, name: 'Kids', category: 'LINEA' },
];

export default tagsArray;
