env:
  CI: false

name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: ["main"]

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['21.x']

    steps:
      - name: Checkoutgit add .

        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USEERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push FE
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USEERNAME }}/bravasales:${{ github.sha }}

