# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pf-brava-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pfbravasales.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e536102c68a04e2383d0b17289209186 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a2a5d0e5ea25436c981a8ed0f9c731f3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pfbravasales.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e536102c68a04e2383d0b17289209186 }}/pfbravasales:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pf-brava-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5613282695724237a84cec1735a1ba92 }}
        images: 'pfbravasales.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e536102c68a04e2383d0b17289209186 }}/pfbravasales:${{ github.sha }}'