name: Server PR CI

on:
  push:
    paths: 'backend/**'
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i
        working-directory: 'backend'
      - run: npm run lint
        working-directory: 'backend'
      - run: npm run format
        working-directory: 'backend'
      - run: npm run test
        working-directory: 'backend'
